//
// Created by jnannie on 12/24/20.
//

int main() {
	try
	{

	}
	catch (std::exception & e)
	{

	}
}
